server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://10.85.60.2:3306/test?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: Aqjcydmm@123
    driver-class-name: com.mysql.cj.jdbc.Driver
tokenHead: Bearer
tokenHeader: Authorization